### ISSUE TITLE
issue with importing Iterable

### ISSUE THREAD

**Issue by bekraoui** [takaakiaoki/ofblockmeshdicthelper#16]
Traceback (most recent call last):
  File "geo.py", line 1, in <module>
    from ofblockmeshdicthelper import BlockMeshDict, Vertex, SimpleGrading
  File "C:\Users\AAAA\AppData\Roaming\Python\Python312\site-packages\ofblockmeshdicthelper\__init__.py", line 6, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (C:\Program Files\Python312\Lib\collections\__init__.py)

solution:

https://stackoverflow.com/questions/72032032/importerror-cannot-import-name-iterable-from-collections-in-python

replace :

`from collections import Iterable`

by:

```
try:
    from collections.abc import Iterable
except ImportError:
    from collections import Iterable
```

**Comment by bekraoui** [comment]
my mistake. i installed for python3 zusing :
pip install ofblockmeshdicthelper
instead of :
pip install 'ofblockmeshdicthelper @ git+https://github.com/takaakiaoki/ofblockmeshdicthelper.git'
